apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_KEY: cGFzc3dvcmRBbnl0aGluZw==
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_KEY: c2tfdGVzdF81MUtJdlFUS0wyMDdUS0ZwNG5nNkNPUDR2bHZwYUZtZHR6Q2thcUVYNzRhbXFiZklGYXRoTm9FTk14cWpjdUdqQUl0VmE4UTBYNWp3Mk01a2tkMTJCQmRpWTAwT094RUVacVE=

